services:
  mysql:
    image: mysql:latest
    container_name: userdb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: user_service
    networks:
      - net
    ports:
      - "3306:3306"
    volumes:
      - "./UserService/src/main/init.sql:/docker-entrypoint-initdb.d/init.sql"
  java-app:
    image: springbootdemo
    container_name: project-app
    networks:
      - net
    ports:
      - "8080:8080"
  user-service:
    build:
      context: UserService
      dockerfile: Dockerfile
    image: userservice
    depends_on :
      - mysql
    container_name: user-service
    networks:
      - net
    ports:
      - "9090:9090"
  auth-service:
    build:
      context: AuthService
      dockerfile: Dockerfile
    image: authservice
    depends_on:
      - mysql
    container_name: auth-service
    networks:
      - net
    ports:
      - "8081:8081"
networks:
  net:
    driver: bridge

    shop-service:
      build:
        context: ShopService
        dockerfile: Dockerfile
      depends_on:
        - mysql
      container_name: shop-service
      networks:
        - net
      ports:
        - "8080:8080"
    networks:
      net:
        driver: bridge