services:
  shop-service:
    image: shopservice
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop-service
    network_mode: host
    ports:
      - "${SHOP_CONTAINER_PORT}:${SHOP_CONTAINER_PORT}"
    environment:
      - ENV=prod
    env_file:
      - .env
