services:
  mysql:
    image: mysql:latest
    container_name: shopdb
    environment:
      MYSQL_ROOT_PASSWORD: ${DEV_USER_PSWD}
      MYSQL_DATABASE: shop_service
    networks:
      - netw
    ports:
      - "${SHOP_MYSQL_SERVER_PORT}:${SHOP_MYSQL_CONTAINER_PORT}"
    volumes:
      - "./src/main/init.sql:/docker-entrypoint-initdb.d/init.sql"

  shop-service:
    image: shopservice
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    container_name: shop-service
    networks:
      - netw
    ports:
      - "${SHOP_SERVER_PORT}:${SHOP_CONTAINER_PORT}"
    env_file:
      - "ENV=DEV"
      - .env

networks:
  netw:
    external: true
    driver: bridge
