services:
  mysql:
    image: mysql:latest
    container_name: shopdb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shop_service
    networks:
      - net
    ports:
      - "3306:3306"
    volumes:
      - "./src/main/init.sql:/docker-entrypoint-initdb.d/init.sql"

  shop-service:
    build:
      dockerfile: Dockerfile
    image: shopservice
    depends_on:
      - mysql
    container_name: shop-service
    networks:
      - net
    ports:
      - "8080:8080"

networks:
  net:
    driver: bridge