services:
  mysql:
    image: mysql:latest
    container_name: shopdb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shop_service
    networks:
      - ${NETWORK_NAME}
    ports:
      - "${SHOP_MYSQL_SERVER_PORT}:${SHOP_MYSQL_CONTAINER_PORT}"
    volumes:
      - "./src/main/init.sql:/docker-entrypoint-initdb.d/init.sql"
  shop-service:
    image: shopservice
    depends_on:
      - mysql
    container_name: ${SHOP_CONTAINER}
    networks:
      - ${NETWORK_NAME}
    ports:
      - "${SHOP_SERVER_PORT}:${SHOP_CONTAINER_PORT}"
    env_file:
      - .env
networks:
  netw:
    driver: bridge
    external: true
