services:
  rabbitmq-service:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    networks:
      - netw
    ports:
    - ${RABBITMQ_AMQ_PORT}:${RABBITMQ_AMQ_PORT}
    - ${RABBITMQ_DASHBOARD_PORT}:${RABBITMQ_DASHBOARD_PORT}
    env_file:
      - .env
    #register this with eurika
    volumes:
    - ./eurika_registration.sh:/usr/local/bin/eurika_registration.sh
    command: rabbitmq-server && /bin/bash /usr/local/bin/eurika_registration.sh
networks:
  netw:
    external: true
    driver: bridge
