services:
  mysql:
    image: mysql:latest
    container_name: messagingDB
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: messaging_service
    networks:
      - ${NETWORK_NAME}
    ports:
      - "${MSG_MYSQL_SERVER_PORT}:${MSG_MYSQL_CONTAINER_PORT}"
    volumes:
      - "./src/main/init.sql:/docker-entrypoint-initdb.d/init.sql"

  messaging-service:
    image: msgservice
    container_name: ${MSG_CONTAINER}
    depends_on:
      - mysql
    networks:
      - ${NETWORK_NAME}
    ports:
      - "${MSG_SERVER_PORT}:${MSG_CONTAINER_PORT}"
    env_file:
      - .env
networks:
  netw:
    driver: bridge
    external: true