services:
  mysql:
    image: mysql:latest
    container_name: userdb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: messaging_service
    networks:
      - net
    ports:
      - "3306:3306"
    volumes:
      - "./MessagingService/src/main/init.sql:/docker-entrypoint-initdb.d/init.sql"

  messaging-service:
    build:
      dockerfile: Dockerfile
    container_name: messaging-service
    depends_on:
      - mysql
    networks:
      - net
    ports:
      - "8080:8080"
networks:
  net:
    driver: bridge