services:
  messaging-service:
    image: msgservice
    container_name: msgservice
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - netw
    ports:
      - "${MSG_SERVER_PORT}:${MSG_CONTAINER_PORT}"
    environment:
      - ENV=prod
    env_file:
      - .env

networks:
  netw:
    driver: bridge
