services:
  mysql:
    image: mysql:latest
    container_name: messagingDB
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: messaging_service
    networks:
      - netw
    ports:
      - "${MSG_MYSQL_SERVER_PORT}:${MSG_MYSQL_CONTAINER_PORT}"
    volumes:
      - "./src/main/init.sql:/docker-entrypoint-initdb.d/init.sql"

  messaging-service:
    image: msgservice
    container_name: msgservice
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    networks:
      - netw
    ports:
      - "${MSG_SERVER_PORT}:${MSG_CONTAINER_PORT}"
    env_file:
      - .env
networks:
  netw:
    external: true
    driver: bridge
