services:
  mysql:
    image: mysql:latest
    container_name: paymentdb
    environment:
      MYSQL_ROOT_PASSWORD: ${USER_PSWD}
      MYSQL_DATABASE: payment_service
    networks:
      - ${NETWORK_NAME}
    ports:
      - "${PAYMENT_MYSQL_SERVER_PORT}:${PAYMENT_MYSQL_CONTAINER_PORT}"
    volumes:
      - "./src/main/init.sql:/docker-entrypoint-initdb.d/init.sql"

  payment-service:
    image: paymentsvc:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PAYMENT_CONTAINER}
    depends_on:
      - mysql
    networks:
      - ${NETWORK_NAME}
    ports:
      - "${PAYMENT_SERVER_PORT}:${PAYMENT_CONTAINER_PORT}"
    env_file:
      - .env

networks:
  netw:
    driver: bridge
    external: true
