services:
  ban-service:
    image: banservice
    container_name: ban-service
    networks:
      - netw
    ports:
      - "${BAN_SERVER_PORT}:${BAN_CONTAINER_PORT}"
    environment:
      - ENV=prod
    env_file:
      - .env

networks:
  netw:
    driver: bridge