services:
  mysql:
    image: mysql:latest
    container_name: bandb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ban_service
    networks:
      - netw
    ports:
      - "${BAN_MYSQL_SERVER_PORT}:${BAN_MYSQL_CONTAINER_PORT}"
    volumes:
      - "./src/main/init.sql:/docker-entrypoint-initdb.d/init.sql"
  ban-service:
    image: banservice
    depends_on :
      - mysql
    container_name: ban-service
    networks:
      - netw
    ports:
      - "${BAN_SERVER_PORT}:${BAN_CONTAINER_PORT}"
    env_file:
      - .env
networks:
  netw:
    driver: bridge