services:
  order-service:
    image: orderservice
    container_name: order-service
    networks:
      - netw
    ports:
      - "${ORDER_CONTAINER_PORT}:${ORDER_CONTAINER_PORT}"
    environment:
      - ENV=prod
    env_file:
      - .env

networks:
  netw:
    driver: bridge
