services:
  mysql:
    image: mysql:latest
    container_name: orderdb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: order_service
    networks:
      - ${NETWORK_NAME}
    ports:
      - "${TRANSACTION_MYSQL_SERVER_PORT}:${TRANSACTION_MYSQL_CONTAINER_PORT}"
    volumes:
      - "./src/main/init.sql:/docker-entrypoint-initdb.d/init.sql"
  order-service:
    image: orderservice
    depends_on:
      - mysql
    container_name: ${ORDER_CONTAINER}
    networks:
      - ${NETWORK_NAME}
    ports:
      - "${ORDER_SERVER_PORT}:${ORDER_CONTAINER_PORT}"
    env_file:
      - .env
networks:
  netw:
    driver: bridge
    external: true
