services:
  rating-service:
    image: ratingsvc
    container_name: rating-service
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - netw
    ports:
      - "${RATE_SERVER_PORT}:${RATE_CONTAINER_PORT}"
    environment:
      - ENV=prod
    env_file:
      - .env

networks:
  netw:
    driver: bridge