services:
  mysql:
    image: mysql:latest
    container_name: userdb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: user_service
    networks:
      - netw
    ports:
      - "3306:3306"
    volumes:
      - "./src/main/init.sql:/docker-entrypoint-initdb.d/init.sql"
  user-service:
    image: userservice
    depends_on :
      - mysql
    container_name: user-service
    networks:
      - netw
    ports:
      - "9090:9090"
networks:
  netw:
    driver: bridge
    external: true