services:
  user-service:
    image: userservice
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    network_mode: host
    ports:
      - "${USER_CONTAINER_PORT}:${USER_CONTAINER_PORT}"
    environment:
      - ENV=prod
    env_file:
      - .env
