spring:
  server:
    port: ${API_GATEWAY_SERVER_PORT}
  application:
    name: api-gateway-service
  profiles:
    active: ${ENV}
  cloud:
    config:
      name: gateway
    gateway:
      routes:
        # User Service Route
        - id: user-service
          uri: lb://user-service:${USER_SERVER_PORT}
          predicates:
            - Path=/users/** #any req to gateway at /users/** path it will go to user service

        # Shop Service Route
        - id: shop-service
          uri: lb://shop-service:${SHOP_SERVER_PORT}
          predicates:
            - Path=/shop/**

        # Messaging Service Route
        - id: msg-service
          uri: lb://msg-service:${MSG_SERVER_PORT}
          predicates:
            - Path=/messages/**

        # Ban Service Route
        - id: ban-service
          uri: lb://ban-service:${BAN_SERVER_PORT}
          predicates:
            - Path=/ban/**

        # Auth Service Route
        - id: auth-service
          uri: lb://auth-service:${AUTH_SERVER_PORT}
          predicates:
            - Path=/auth/**

        # Order Service Route
#        - id: ${ORDER_CONTAINER}
#          uri: lb://${ORDER_CONTAINER}:${ORDER_SERVER_PORT}
#          predicates:
#            - Path=/order/**

        # Transaction Service Route
#        - id: ${TRANSACTION_CONTAINER}
#          uri: lb://${TRANSACTION_CONTAINER}:${TRANSACTION_SERVER_PORT}
#          predicates:
#            - Path=/auth/**

        # Payment Service Route
#        - id: ${PAYMENT_CONTAINER}
#          uri: lb://${PAYMENT_CONTAINER}:${PAYMENT_SERVER_PORT}
#          predicates:
#            - Path=/payment/**


#eureka:
#  client:
#    service-url:
#      defaultZone: http://${EUREKA_CONTAINER}:${EUREKA_SERVER_PORT}/eureka/
