services:
#  mysql:
#    image: mysql:latest
#    container_name: authdb
#    environment:
#      MYSQL_ROOT_PASSWORD: 1234
#      MYSQL_DATABASE: auth_service
#    networks:
#      - net
#    ports:
#      - "3306:3306"
#    volumes:
#      - "./src/main/init.sql:/docker-entrypoint-initdb.d/init.sql"

  auth-service:
    build:
      dockerfile: Dockerfile
    image: authservice
    container_name: auth
    networks:
      - net
    ports:
      - "8081:8081"
#    depends_on:
#      - mysql

networks:
  net:
    driver: bridge
    external: true
