services:
  auth-service:
    build:
      dockerfile: Dockerfile
    image: authservice
    container_name: auth-service
    networks:
      - netw
    ports:
      - "${AUTH_CONTAINER_PORT}:${AUTH_CONTAINER_PORT}"
    environment:
      - ENV=prod
    env_file:
      - .env

networks:
  netw:
    driver: bridge
