
on:
  pull_request:
    branches: [ "main" ]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Testing pls delete
      run: ls -la
      
    - name: Changing Directory
      run: cd MessagingService

    - name: Testing pls delete2
      run: ls -la
      
    - name: Give gradlew Permissions
      run: sudo chmod +x gradlew

    - name: Execute Gradle build
      run: ./gradlew build

    - name: Build the Docker image
      run: docker build -t springbootdemo .
