
on:
  pull_request:
    branches: [ "main" ]

jobs:
  Pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Execute Gradle build
      run: |
        sudo chmod +x gradlew
        ./gradlew build

    - name: Build the Messaging Service Docker image
      run: docker build -f ./MessagingService/Dockerfile ./MessagingService/

    - name: Build the User Service Docker image
      run: docker build -f ./UserService/Dockerfile ./UserService/
